name = "jsp_000992_formalization"
version = "0.1.0"
defaultTargets = ["Challenge", "Submission"]

[[lean_lib]]
name = "Challenge"
srcDir = "."
roots = ["Challenge"]

[[lean_lib]]
name = "Submission"
srcDir = "."
roots = ["Submission"]
